name: ai_learning_companion
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # this package is used to manage routes in the application
  # it allows for declarative routing and deep linking
  go_router: ^15.2.0

  flutter_native_splash: ^2.4.6
  # this package is used to manage local storage in the application
  shared_preferences: ^2.5.3
  # this package is used to display an animated lottie
  lottie: ^3.3.1
  get_it: ^8.0.3
  # this package is used for adapting screen and font size
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
